Abdulov homework
Azadios/hh-school-2020-java-collections-stream pull request #1
Opened 2020-11-26 12:41 UTC by Azadios

Сделал все задания. Комментарии написаны в коде.

2020-11-28 17:23 UTC, genroelgvozo requested changes

2020-11-28 17:23 UTC, genroelgvozo commented on src/tasks/Task1.java
> +    List<Person> personsSortedById = personIds.stream()
Единственное вопрос, что будет если не для всех айди мы найдем персоны?

2020-11-28 17:23 UTC, genroelgvozo commented on src/tasks/Task2.java
>    private static List<Person> combineAndSortWithLimit(Collection<Person> persons1,
Вопросов нет)

2020-11-28 17:23 UTC, genroelgvozo commented on src/tasks/Task3.java
>    private List<Person> sort(Collection<Person> persons) {
Вопросов нет)

2020-11-28 17:23 UTC, genroelgvozo commented on src/tasks/Task4.java
>    private List<ApiPersonDto> convert(List<Person> persons) {
Вопросов нет)

2020-11-28 17:23 UTC, genroelgvozo commented on src/tasks/Task5.java
> +          .map(x -> convert(x, personAreaIds.get(x.getId())))
даже локальные переменные в таких случаях (когда имеют смысл и используются в осмысленных методах) лучше называть осмысленно, типо person

2020-11-28 17:23 UTC, genroelgvozo commented on src/tasks/Task6.java
> +              Stream.Builder<String> personDescriptions = Stream.builder();
Очень сложно выглядит) 
и долго
Твой код для каждой персоны бежит по всем арейкам, и каждый раз создает мапу, которая вообщем-то от персон не зависит, и ее можно заранее создать
И билдер тут не понял зачем, если можно вместо форич использовать мап, и как раз этот стрим пойдет во флатмап

2020-11-28 17:23 UTC, genroelgvozo commented on src/tasks/Task7.java
> +      companie.getVacancies().forEach(vacancy -> vacancyNames.add(vacancy.getTitle()));
а тоже самое но через стримы?) ты уже использовал что-то в предыдущей задачи, что позволит тебе сделать все в три строки через стримы

2020-11-28 17:23 UTC, genroelgvozo commented on src/tasks/Task8.java
> +А некоторым придется читать код, написанный мною (Уверен, он не так уж и плох на самом деле ;) )
Но не сегодня!

2020-11-28 17:23 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    // будет оптимизировано удаление первого элемента из List'а (но это не точно :) )
Про оптимизацию да, и так будет О(н), так как проход будет с мап и сборкой в лист. Не надо предварительно удалять и двигать, но асимптотически суммарно все вместе одинаково
А про смену входной коллекции это как раз ценное замечание, это плохой паттерн когда меняешь параметры

2020-11-28 17:23 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    // Не понимаю к чему distinct, set сам по себе даст уникальные значения
Я тоже все понимаю) все ок

2020-11-28 17:23 UTC, genroelgvozo commented on src/tasks/Task8.java
> +  // not cool man
последний факт как раз таки нет, лучше null чем ""
Все таки отсутствие чего-то != пустое что-то. Если пытаться в базе хранить пустые строки а не налл, это шанс ошибиться, и часть строк сохранить с null (по умолчанию то объекты в null будут)
Ну и идеологически как сказал отсутствие это null в джаве

2020-11-28 17:23 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    // Стоило бы узнать наверняка, а не предполагать, но кто вообще будет использовать это?
да просто в разных отчетах нужно ФИО, это не toString у Person (вообще toString использовать в таких случаях это плохо, тустринг все таки для логгирования, текстового представления всей персоны, а не только ФИО, а это именно конвертер для каких-то конкретных целей)
Какое-то странное чувство вызвало у тебя эта функция, вполне нормальная)
Но написана не очень, иногда во-первых работает не правильно (пробел может быть в начале), а во-вторых выглядит как-то не очень, ифы, какие-то пробелы. Хочется элегантного кода, а мы как раз тут стримы прошли..))

2020-11-28 17:23 UTC, genroelgvozo commented on src/tasks/Task8.java
>    public Map<Integer, String> getPersonNames(Collection<Person> persons) {
Ну уже лучше, но все таки, эти куча строк можно записать одной, опять же не зря стрим апи мы прошли)

2020-11-28 17:23 UTC, genroelgvozo commented on src/tasks/Task8.java
> +  // и вроде как have, а не has правильно, но я не силён в английский. Скорее на подумать.
Ни разу не видел have
Вроде тут все объекты, поэтому неодушевленные it has

2020-11-28 17:23 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    return !Collections.disjoint(persons1, persons2);
Вопрос - за сколько работает изначальный код, и за сколько твой?

2020-11-28 17:23 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    return numbers.filter(num -> num % 2 == 0).count();
Коммент плиз) почему плохо было делать как было

2020-11-29 06:52 UTC, Azadios commented on src/tasks/Task5.java
> +          .map(x -> convert(x, personAreaIds.get(x.getId())))
Не понимаю, почему оставил так. Конечно же, лучше person.

2020-11-29 06:52 UTC, Azadios commented on src/tasks/Task6.java
> +              Stream.Builder<String> personDescriptions = Stream.builder();
Мозг выключился) Исправлю

2020-11-29 06:54 UTC, Azadios commented on src/tasks/Task7.java
> +      companie.getVacancies().forEach(vacancy -> vacancyNames.add(vacancy.getTitle()));
Вы там, конечно, сами решайте когда чего, но решайте в пользу стримов)
Договорились, сделаю через стримы.

2020-11-29 06:58 UTC, Azadios commented on src/tasks/Task8.java
> +    // будет оптимизировано удаление первого элемента из List'а (но это не точно :) )
Асимптотически - да, как раз имел в виду удалять и двигать.
И да, ужасно однажды осознать, что входные данные не очень-то входные и не очень-то данные)

2020-11-29 07:00 UTC, Azadios commented on src/tasks/Task1.java
> +    List<Person> personsSortedById = personIds.stream()
Map будет выдавать null. Если по логике (которую я поддерживаю) нужен null-object, то стоит использовать getOrDefault

2020-11-29 07:07 UTC, Azadios commented on src/tasks/Task8.java
> +  // not cool man
В общем случае согласен, что отсутствие != пустое, но в разве пустое поле в фио не значит отсутствие этого поля?
Про базы согласен.
Просто мне кажется, что null часто ломает абстракцию. Но да, это, видимо, не лучшее место для nullObject'а

2020-11-29 07:36 UTC, Azadios reviewed
Я сначала просто комментил каждый момент, но потом обнаружил, что могу всех их в ревью запихнуть.
Последнее, как я понимаю, лучше?

2020-11-29 07:36 UTC, Azadios commented on src/tasks/Task8.java
> +    // Стоило бы узнать наверняка, а не предполагать, но кто вообще будет использовать это?
Да, меня сам код триггернул, вот и написал всякого) Перепишу через стримы.

2020-11-29 07:36 UTC, Azadios commented on src/tasks/Task8.java
>    public Map<Integer, String> getPersonNames(Collection<Person> persons) {
Сделаю

2020-11-29 07:36 UTC, Azadios commented on src/tasks/Task8.java
> +  // и вроде как have, а не has правильно, но я не силён в английский. Скорее на подумать.
У меня в голове это выглядело как it has/they have.
Но это совсем grammarNazi придирка от меня :)

2020-11-29 07:36 UTC, Azadios commented on src/tasks/Task8.java
> +    return !Collections.disjoint(persons1, persons2);
Изначальный Θ(n^2).
Мой O(n^2)
Можно перебросить один из них в сет, тогда будет линейно, просто решил, что пока профилировщик не сказал, что медленно, то лучше понятный и медленный код, чем быстрый и не обязательно понятный.

2020-11-29 07:36 UTC, Azadios commented on src/tasks/Task8.java
> +    return numbers.filter(num -> num % 2 == 0).count();
Ну как минимум должно было насторожить, что лямбда в forEach не изпользует аргумент.
count обычно очень быстрая операция, а то что было займёт линейное время. Да и нечитабельно.
А ещё, не знаю меняет ли java дебаг код, но в си постфиксный инкремент может продлить дебаг из-за нулевой оптимизации, а значит трёх инструкций вместо двух :)

2020-11-29 08:00 UTC, Azadios commented on src/tasks/Task5.java
> +          .map(x -> convert(x, personAreaIds.get(x.getId())))
Fixed

2020-11-29 08:05 UTC, Azadios commented on src/tasks/Task7.java
> +      companie.getVacancies().forEach(vacancy -> vacancyNames.add(vacancy.getTitle()));
Done

2020-11-29 08:33 UTC, Azadios commented on src/tasks/Task8.java
> +    // Стоило бы узнать наверняка, а не предполагать, но кто вообще будет использовать это?
Done

2020-11-29 08:53 UTC, Azadios commented on src/tasks/Task8.java
>    public Map<Integer, String> getPersonNames(Collection<Person> persons) {
Done

2020-11-29 09:13 UTC, Azadios commented on src/tasks/Task6.java
> +              Stream.Builder<String> personDescriptions = Stream.builder();
Done

2020-12-04 17:45 UTC, genroelgvozo commented on src/tasks/Task1.java
> +    List<Person> personsSortedById = personIds.stream()
null объект точно плохо, это что это, не нашлась персона, вместо нее фальшивку подсунем?) может вообще не должно быть ни налл ни чего бы то еще

2020-12-04 17:52 UTC, genroelgvozo approved these changes

2020-12-04 17:52 UTC, genroelgvozo commented on src/tasks/Task8.java
> +          .filter(name -> name != null)
Objects::nonNull - говорящее)

2020-12-04 17:52 UTC, genroelgvozo commented on src/tasks/Task8.java
> +                                    (presentName, newName) -> presentName));
все гуд)

2020-12-04 17:52 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    return !Collections.disjoint(persons1, persons2);
ну Collections.disjoint еще над знать что делает, тоже непонятно) (хотя я согласен)
Обернуть один параметр в new HashSet не сильно усложнит
еще вариант - persons1.stream().anyMatch(new HashSet<>(persons2)::contains);

2020-12-04 17:52 UTC, genroelgvozo commented on src/tasks/Task8.java
> +    return numbers.filter(num -> num % 2 == 0).count();
тут все проще, исходный код иногда неправильно считал ответ, передай ему stream().parallel()...
А вот о трех операциях в дебаге точно не надо думать О_о

2020-12-04 17:54 UTC, Azadios commented on src/tasks/Task8.java
> +          .filter(name -> name != null)
Учту

2021-05-09 02:21 UTC, closed without merging